# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: devopsified-gowebapp
  labels:
    app: devopsified-gowebapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: devopsified-gowebapp
  type: ClusterIP